name: Ubuntu CI

on:
  push:
    branches: [ "main", "tmp8" ]
  pull_request:
    branches: [ "main", "tmp8" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: clone_golang
      run: git clone -b go1.17.8 --single-branch https://github.com/golang/go ../go
    - name: clone_python
      run: git clone -b v3.9.12 --single-branch https://github.com/python/cpython ../cpython
    - name: install_deps
      run: ./deps_ubuntu.sh
    - name: make_single_test
      run: make -j8 build/unittest_lang
    - name: single_test1
      run: build/unittest_lang golang_if_func_assoc2
    - name: single_test2
      run: build/unittest_lang calc
    - name: single_test3
      run: build/unittest_lang xfail_lexer_cycle
    - name: bootstrap
      run: ./bootstrap.sh
